---
title: Bosc Negre Web
timezone: Europe/Paris
collections:
  gites:
    title: FR_cottages
    output: true
  articles:
    title: FR_news
    output: true
  fr:
    title: FR_pages
    output: true
  services:
    title: FR_services
    output: true
  posts:
    title: NL_news
    output: true
  huisjes:
    title: NL_cottages
    output: true
  nl:
    title: NL_pages
    output: true
  diensten:
    title: NL_services
    output: true
  uploads:
    title: Uploads
    output: true
